# 应用服务 WEB 访问端口
server:
  port: 8083

spring:
  application:
    name: freedom-producer
freedom:
  registry:
    host: localhost
    name: ${spring.application.name}
    port: ${server.port}
    destinationAddress: 127.0.0.1:8888
    health:
      heartbeat: true
    router:
      type: random

